version: '0.1'

services:
  # Nginx Load Balancer
  nginx-lb:
    image: nginx@sha256:4d5c9a3437fc6b4d886c7c65ca59a1851120e9e63a4951a7d7cb7a4155501383
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pizza-network
    depends_on:
      - nginx1
      - nginx2

  # Nginx Servers
  nginx1:
    image: nginx@sha256:4d5c9a3437fc6b4d886c7c65ca59a1851120e9e63a4951a7d7cb7a4155501383
    container_name: nginx1
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pizza-network

  nginx2:
    image: nginx@sha256:4d5c9a3437fc6b4d886c7c65ca59a1851120e9e63a4951a7d7cb7a4155501383
    container_name: nginx2
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pizza-network

  # Node.js Backend
  backend:
    image: node@sha256:3ac002b133fd3737c44b66f0d023f5d75c7a1ddec71954fa06486aed6aead888
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - REDIS_HOST=pepperoni
      - REDIS_PORT=6379
      - POSTGRES_HOST=mushroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fridge
    networks:
      - pizza-network
    depends_on:
      - redis
      - postgres

    worker:
    image: node@sha256:3ac002b133fd3737c44b66f0d023f5d75c7a1ddec71954fa06486aed6aead888
    container_name: worker
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - REDIS_HOST=pepperoni
      - REDIS_PORT=6379
      - POSTGRES_HOST=mushroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fridge
    networks:
      - pizza-network
    command: node worker.js
    depends_on:
      - redis
      - postgres

  # Redis
  redis:
    image: redis@sha256:bb226f09bb6370390843a16a91cddef7d4c2ee3cbe8e3d4814e971386d866c7b
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pizza-network
    hostname: pepperoni

  # PostgreSQL
  postgres:
    image: postgres@sha256:2f2a8c2a7d10862e7fba2602e304523554f9df8244c632dafe2628ccb398fb5c
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fridge
    volumes:
      - /data/postgresql/cdv-fridge-composer:/var/lib/postgresql/data
    networks:
      - pizza-network
    hostname: mushroom

# Custom Docker Network
networks:
  pizza-network:
    driver: bridge