version: '3.8'

# Custom Docker Network
networks:
  pizza-network:
    driver: bridge

services:
  # Nginx server
  nginx:
    build: ./frontend
    container_name: cashier-nginx
    ports:
      - "80:80"
    networks:
      - pizza-network
    hostname: cashier


  # Node.js Backend
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: oven-backend
    environment:
      - REDIS_HOST=pepperoni
      - REDIS_PORT=6379
      - POSTGRES_HOST=mushroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fridge
    networks:
      - pizza-network
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    hostname: oven

  # Redis
  redis:
    image: redis@sha256:bb226f09bb6370390843a16a91cddef7d4c2ee3cbe8e3d4814e971386d866c7b
    container_name: pepperoni-redis
    ports:
      - "6379:6379"
    networks:
      - pizza-network
    hostname: pepperoni

  # PostgreSQL
  postgres:
    image: postgres@sha256:2f2a8c2a7d10862e7fba2602e304523554f9df8244c632dafe2628ccb398fb5c
    container_name: mushroom-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fridge
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pizza-network
    hostname: mushroom
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fridge"]
      interval: 5s
      timeout: 5s
      retries: 5